### ISSUE TITLE
User Class 

### ISSUE THREAD

**Issue by lhao03** [UBC-BEST/frontend-m2m#1]
## Specification 
The User class will hold user information such as personal information and tokens/uid for user authentication. You will have to work with the User Auth people in the backend to implement this class completely. 
#### Methods
- ` bool isUserAuthenticated() `
- ` syncUserChanges()`
#### Attributes 
-  `String name`
-  `Dict metaData`
- `String token`
- ` Dict dataToSync` 
## Todo
- [ ] implement user class
- [ ] include tests for each method
- [ ] include docstrings for each method

**Comment by lhao03** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User Class](https://trello.com/c/pP0irPU3/12-user-class)
