### ISSUE TITLE
Login/Signup Page 

### ISSUE THREAD

**Issue by lhao03** [UBC-BEST/frontend-m2m#13]
# Description
- there needs to be some kind of validation so only users with accounts can login. 
- also only registered users should be able to see the home page 

## Todo
- [ ] first implement this without the database. Make sure your code is not too coupled. This means there should be almost no need to refactor  when we actually have a database working. Ask @lhao03 to double check you don't have too much coupling. 
- [ ] to mimic data collection use arraylists to hold usernames and passwords 
- [ ] using preexisting classes and stubs make methods that can validate a user, create a user, log a user out 
- [ ] more to come... 

## deliverable
- demo of login/signup process
