### ISSUE TITLE
FAQ Page for our app 

### ISSUE THREAD

**Issue by lhao03** [UBC-BEST/frontend-m2m#15]
# description 
- when a new user creates an account or a user wants to know more about our app, they will go to the faq! 
- this task can be ongoing as we are developing the app and adding features 

##  Todo 
- [ ] create list of questions users could have 
- [ ] make a screen to present these questions with answers. Make this screen very easy to use 

## deliverable 
- [ ] demo of FAQ screen
