### ISSUE TITLE
Sensor Class

### ISSUE THREAD

**Issue by lhao03** [UBC-BEST/frontend-m2m#2]
## Specification 
The Sensor class should have will deal with bluetooth connectivity for the sensor. To implement this class, create a simple screen that will allow the user to click it to connect any bluetooth device. Bonus points if you can make the bluetooth device interact with the app. 

### Methods
- ` findDevices() `
- ` connectDevice(name) `
- ` read() `
- ` save() ` 

## Todo
- [ ] implement Sensor class
- [ ] include tests for each method
- [ ] include docstrings for each method
