### ISSUE TITLE
Session Class 

### ISSUE THREAD

**Issue by lhao03** [UBC-BEST/frontend-m2m#3]
## Specification 
Every time the user starts a game, we will run an instance of the Session class to track their data or load data into the game. 

### Methods
- ` createSession(game, sensor) `
- ` saveSessionData() `
- ` endSession() `
## Todo
- [ ] implement Session class
- [ ] include tests for each method
- [ ] include docstrings for each method
