### ISSUE TITLE
Game Class/Interface

### ISSUE THREAD

**Issue by lhao03** [UBC-BEST/frontend-m2m#4]
## Specification 
The Game Class is represents each game we will have in the app. The Game Class mostly acts as a super class that other classes will extend once we have our games. This class may or may not be needed. It is supposed to be generic to support inheritance. 

#### Methods
- ` getScore()`
- ` getMetadata() `
## Todo
- [ ] implement Game class
- [ ] include tests for each method
- [ ] include docstrings for each method
