### ISSUE TITLE
User Onboarding 

### ISSUE THREAD

**Issue by lhao03** [UBC-BEST/frontend-m2m#8]
For this task, work together with UI/UX to create a user onboarding for our app. When the user creates an account (you use mock user authentication), the user is prompted to enter more details. Information includes age, MS severity, etc. You don't need to make the app look polished, but have all the screens working. 

### Todo
- [ ] Use the User class to collect this information
- [ ] Create navigations between screens to collect this information 

### Deliverable
- [ ] Simple walkthrough of app in which the user is creating a new profile/account. 

#1

**Comment by lhao03** [comment]
@AllisonSimpson I've updated the issue with a tutorial! The UI/UX doesnt have to be fully implemented. We want a MVP at this point.

**Comment by lhao03** [comment]
@mattmajo I'm adding you to this issue because you have the most knowledgeable on patients on what types of data collection would be useful!

**Comment by lhao03** [comment]
![image](https://user-images.githubusercontent.com/55033656/99885219-9fea2600-2bf0-11eb-998d-0df71ae7ae70.png)
this is what i have in the schema to put in the database. @AllisonSimpson 
msScore is the MS score you were mentioning, 
and selfAssesmentScore is the score if someone took a self assessment of MS (might be refined in the future)
miscInfo is anything else. Please correct or change anything to your research!
